/**
 * Data access for `outside_views` (ADR 0002).
 *
 * The Outside View is a portal-resident, persistent diagnostic artifact
 * generated by the /scan pipeline at D1 depth and (Phase 3) by the
 * conversational agent at D2 depth.
 *
 * v1 storage shape: `artifact_json` holds the existing `RenderedReport`
 * shape from `src/lib/diagnostic/render.ts` serialized as JSON. v2 will
 * be the canonical five-field-per-observation contract from ADR 0002 §3.
 * The version dispatch lives in the adapter at
 * `src/lib/db/outside-views/adapter.ts` — never read or write
 * `artifact_json` directly.
 *
 * See migrations/0032_create_outside_views.sql for field semantics.
 */

export type OutsideViewDepth = 'd1' | 'd2' | 'd3'

export interface OutsideView {
  id: string
  org_id: string
  entity_id: string
  scan_request_id: string | null
  depth: OutsideViewDepth
  artifact_version: number
  artifact_json: string
  rendered_at: string
  created_at: string
}

export interface CreateOutsideViewInput {
  org_id: string
  entity_id: string
  scan_request_id?: string | null
  depth: OutsideViewDepth
  artifact_version?: number
  artifact_json: string
  rendered_at: string
}

/**
 * Insert a new outside_views row. Returns the inserted row.
 *
 * Callers should use the adapter (`renderedReportToArtifactJsonV1`) to
 * produce `artifact_json` rather than serializing inline — keeps the
 * version contract honest.
 */
export async function createOutsideView(
  db: D1Database,
  input: CreateOutsideViewInput
): Promise<OutsideView> {
  const id = crypto.randomUUID()
  const version = input.artifact_version ?? 1

  await db
    .prepare(
      `INSERT INTO outside_views (
        id, org_id, entity_id, scan_request_id,
        depth, artifact_version, artifact_json, rendered_at
      )
      VALUES (?, ?, ?, ?, ?, ?, ?, ?)`
    )
    .bind(
      id,
      input.org_id,
      input.entity_id,
      input.scan_request_id ?? null,
      input.depth,
      version,
      input.artifact_json,
      input.rendered_at
    )
    .run()

  return {
    id,
    org_id: input.org_id,
    entity_id: input.entity_id,
    scan_request_id: input.scan_request_id ?? null,
    depth: input.depth,
    artifact_version: version,
    artifact_json: input.artifact_json,
    rendered_at: input.rendered_at,
    created_at: new Date().toISOString(),
  }
}

/**
 * Get the most recently rendered outside_views row for a given entity,
 * scoped by org. Returns null if none exist.
 *
 * "Active" in v1 means "most recently created." Phase 4 will introduce
 * `superseded_by` and tighten this to "not superseded" — the function
 * signature stays stable through that change.
 */
export async function getActiveOutsideViewByEntity(
  db: D1Database,
  orgId: string,
  entityId: string
): Promise<OutsideView | null> {
  const row = await db
    .prepare(
      `SELECT * FROM outside_views
       WHERE org_id = ? AND entity_id = ?
       ORDER BY created_at DESC
       LIMIT 1`
    )
    .bind(orgId, entityId)
    .first<OutsideView>()

  return row ?? null
}

/**
 * Get an outside_views row by its scan_request_id. Used by the workflow
 * shadow-write path to detect re-runs and avoid duplicates.
 */
export async function getOutsideViewByScanRequestId(
  db: D1Database,
  scanRequestId: string
): Promise<OutsideView | null> {
  const row = await db
    .prepare(
      `SELECT * FROM outside_views
       WHERE scan_request_id = ?
       ORDER BY created_at DESC
       LIMIT 1`
    )
    .bind(scanRequestId)
    .first<OutsideView>()

  return row ?? null
}
