-- Migration 0032: Outside View artifact storage (ADR 0002).
--
-- The Outside View is a portal-resident persistent diagnostic artifact.
-- The /scan diagnostic pipeline (#598, shipped 2026-04-27 across PRs
-- #608/#613/#615/#617/#619) renders a `RenderedReport` and currently
-- emails it. Phase 1 of Outside View re-aims that output: instead of
-- email-only, the artifact lives here and renders at
-- portal.smd.services/outside-view.
--
-- Schema versioning. `artifact_version=1` stores the existing
-- `RenderedReport` shape from `src/lib/diagnostic/render.ts` as JSON.
-- v2 will be the canonical five-field-per-observation contract from
-- ADR 0002 §3, migrated forward without backfill. Reads/writes go
-- through the adapter layer at `src/lib/db/outside-views/adapter.ts`,
-- which dispatches by version.
--
-- Field semantics
-- ---------------
-- depth                'd1' (URL-only public-footprint scan), 'd2'
--                      (15-min voice/text conversation), 'd3' (60-min
--                      assessment call). Same artifact shape across
--                      depths; fidelity scales with input.
--
-- scan_request_id      FK to scan_requests.id for D1 rows generated by
--                      the inbound /outside-view form. NULL for D2-only
--                      rows entered directly via referral path
--                      (deferred to Phase 3) or D3 rows authored by
--                      the consultant.
--
-- artifact_version     Version of the JSON shape stored in
--                      artifact_json. Defaults to 1. Adapter-controlled.
--
-- artifact_json        JSON-serialized artifact. v1 = RenderedReport
--                      (5-section structured output preserving anti-fab
--                      guards from #617).
--
-- rendered_at          When the artifact was generated (workflow
--                      completion time for D1; conversation-finalize
--                      time for D2). Distinct from created_at, which
--                      is the row-insertion time.
--
-- NOTE: `superseded_by` is deliberately omitted in v1. Phase 4
-- introduces the "re-run later" flow and will add the column then
-- (per /critique 3 Simplifier #7 — YAGNI).
--
-- NOTE: `completed_d2_at` will be added in Phase 3 (D2 conversational
-- layer) as a nullable column. It replaces a hypothetical
-- `prospect_engaged` role flip with a column-based gate (per
-- /critique 3 Pragmatist #8 — reversible, queryable).
--
-- Indexes
-- -------
-- (entity_id, created_at DESC)   — latest-artifact lookup for portal page
-- (entity_id, depth)             — depth-filtered queries (admin tab)

CREATE TABLE outside_views (
  id                TEXT PRIMARY KEY,
  org_id            TEXT NOT NULL REFERENCES organizations(id),
  entity_id         TEXT NOT NULL REFERENCES entities(id),
  scan_request_id   TEXT REFERENCES scan_requests(id),

  depth             TEXT NOT NULL CHECK (depth IN ('d1', 'd2', 'd3')),
  artifact_version  INTEGER NOT NULL DEFAULT 1,
  artifact_json     TEXT NOT NULL,

  rendered_at       TEXT NOT NULL,
  created_at        TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE INDEX idx_outside_views_entity_recent
  ON outside_views(entity_id, created_at DESC);

CREATE INDEX idx_outside_views_entity_depth
  ON outside_views(entity_id, depth);

CREATE INDEX idx_outside_views_scan_request
  ON outside_views(scan_request_id)
  WHERE scan_request_id IS NOT NULL;
