#!/usr/bin/env bash
# Claims probe — generated by /code-review v2.
#
# Every fact re-derives itself. Two fields govern how a result is read:
#   state:     OPEN  = defect still stands   | FIXED = defect was fixed
#   direction: exact | at-most | at-least    (which way is improvement)
#
#   HOLDS + FIXED -> closed, skipped next run
#   HOLDS + OPEN  -> STILL-OPEN, carried into every report, never skipped
#   DRIFT + FIXED -> regression, loud
#   DRIFT + OPEN  -> improvement or change, re-measure
#
# Usage: bash docs/reviews/claims-2026-10-06.probe.sh
# Exit:  0 = nothing regressed, 1 = a FIXED claim broke or a shape check failed

cd "$(dirname "$0")/../.." || exit 2

pass=0; still_open=0; regressed=0; drift=0
REPORT="docs/reviews/claims-2026-10-06.md"

# ---------------------------------------------------------------- self-check
if [ -f "$REPORT" ]; then
  lines=$(grep -cve '^[[:space:]]*$' "$REPORT")
  grades=$(grep -cE '^\| [A-F][+-]? ' "$REPORT" || true)
  [ "$lines" -le 60 ] || { echo "SHAPE FAIL: report is $lines non-blank lines (max 60)"; exit 1; }
  [ "$grades" -eq 0 ] || { echo "SHAPE FAIL: report contains $grades letter-grade rows"; exit 1; }
  printf '  shape: %s non-blank lines, %s grade rows\n\n' "$lines" "$grades"
fi

# ------------------------------------------------------------------- checker
check() {
  local id="$1" state="$2" dir="$3" expected="$4" actual="$5" desc="$6"
  local ok=1
  case "$dir" in
    exact)    [ "$actual" = "$expected" ] || ok=0 ;;
    at-most)  [ "$actual" -le "$expected" ] 2>/dev/null || ok=0 ;;
    at-least) [ "$actual" -ge "$expected" ] 2>/dev/null || ok=0 ;;
  esac
  if [ "$ok" = 1 ] && [ "$state" = "FIXED" ]; then
    printf '  \033[32mHOLDS     \033[0m %-5s %s (= %s)\n' "$id" "$desc" "$actual"; pass=$((pass+1))
  elif [ "$ok" = 1 ] && [ "$state" = "OPEN" ]; then
    printf '  \033[33mSTILL-OPEN\033[0m %-5s %s (= %s)\n' "$id" "$desc" "$actual"; still_open=$((still_open+1))
  elif [ "$state" = "FIXED" ]; then
    printf '  \033[31mREGRESSED \033[0m %-5s %s expected %s %s, got %s\n' "$id" "$desc" "$dir" "$expected" "$actual"; regressed=$((regressed+1))
  else
    printf '  \033[36mCHANGED   \033[0m %-5s %s was %s %s, now %s — re-measure\n' "$id" "$desc" "$dir" "$expected" "$actual"; drift=$((drift+1))
  fi
}
# count of lines, whitespace-stripped, never failing the pipeline
n() { wc -l | tr -d ' '; }
c() { grep -c "$@" 2>/dev/null | tr -d ' '; }

MC=operator/runners/medchron/medchron
SB=operator/connectors/smokeball/smokeball_connector

echo "Claims for ss-console, 2026-10-06"
echo

# ========================================== CARRIED (closed; regression net)
check PC6 FIXED at-least 1 "$(grep -rniE "content-type|cache-control" src/ workers/ public/ wrangler.toml 2>/dev/null | n)" "instrument is live (sibling header terms found)"
check A6  FIXED at-least 4 "$(grep -rniE "content-security-policy|x-frame-options|strict-transport-security|frame-ancestors" src/ workers/ public/ wrangler.toml 2>/dev/null | n)" "security response headers exist in shipped code"
check A6w FIXED at-least 1 "$(c -E 'return applySecurityHeaders\(response, context\.request\.url\)' src/middleware.ts)" "headers applied by the middleware (call site)"
check F3  FIXED at-least 1 "$(c 'EXPECTED_VERBS' tests/broker-verb-registry.test.ts)" "broker verb set is pinned by a test"
check F4  FIXED at-least 1 "$(c 'taintGateMembers' tests/operator-taint-gate.test.ts)" "taint-gate refusal set is pinned by a test"
check F7  FIXED at-least 20 "$(c '"copies"' operator/contracts/pre-run-shared-symbols.json)" "vendored pre_run symbols under a sync contract"
check F12 FIXED exact 0 "$(c -E '^ *thresholds *:' vitest.config.ts)" "no unevaluatable coverage thresholds declared"
check F15 FIXED at-least 3 "$(c 'redactOpaqueSegments' src/pages/api/events.ts)" "manage-token redaction wired"
check F17 FIXED at-least 1 "$(c '{!disableAnalytics && <EventsTracker />}' src/layouts/Base.astro)" "EventsTracker honours disableAnalytics"
check PCA1 FIXED at-least 1 "$(c smd_subscription_id src/lib/stripe/subscriptions.ts)" "instrument live: checkout stamps smd_subscription_id"
check A1  FIXED at-least 1 "$(c smd_subscription_id src/lib/webhooks/stripe-subscription-handler.ts)" "invoice handler falls back by smd_subscription_id"
check A2  FIXED at-least 1 "$(grep -rn 'payment_status\|async_payment' src/pages/api/webhooks/stripe.ts src/lib/webhooks/ | n)" "checkout completion reads payment_status"
check A3  FIXED exact 0 "$(c 'ON CONFLICT(storage_key) DO UPDATE' src/lib/db/operator-agreements.ts)" "agreement upsert never overwrites an executed document"
check A4  FIXED exact 0 "$(c 'in force together' 'src/pages/portal/products/operator/[instance]/compliance/index.astro')" "no template contractual-status sentence"
check A5  FIXED exact 0 "$(c 'Your subscription is active' src/pages/portal/billing/index.astro)" "no 'active' banner from ?start=done alone"
check B1  FIXED exact 0 "$(c 'picked.append({"id": r.get("id"), "name": name, "pages": r.get("pages")})' $MC/decisions.py)" "billing_docs rows carry the path billing.py renders"
check PCB2 FIXED at-least 1 "$(c 'controls.json' $MC/stages/classify.py)" "instrument live: classify.py names controls.json"
check B2  FIXED at-least 1 "$(grep -l 'controls' $MC/daemon.py $MC/seat.py $MC/job.py operator/workspace_broker/medchron_verbs.py operator/templates/entrypoint.sh operator/templates/Dockerfile operator/bin/provision-customer.sh 2>/dev/null | n)" "a seat-side path seeds medchron controls"
check PCB3 FIXED at-least 1 "$(c skill_name operator/workspace_broker/audit_ledger.py)" "instrument live: the ledger schema has skill_name"
# B3 RESTATED 10-06: skill_name moved server.py -> transmit_verbs.py (the
# 09-04 grep went 1 -> 0 on a refactor, not a regression).
check B3  FIXED at-least 1 "$(c skill_name operator/workspace_broker/transmit_verbs.py)" "broker dispatch rows carry skill_name (transmit_verbs)"
check B4  FIXED at-least 1 "$(c 'return_link_unauthored' operator/skills/client-verification-tracker/render.py)" "CVT treats return_link_unauthored as seat-level"
check B5  FIXED exact 0 "$(c 'Reason: {fields' $MC/daemon.py)" "medchron wake carries no free-text reason"
check B6  FIXED exact 0 "$(c 'we will extend' $MC/stages/limitations.py)" "chronology limitations section makes no future promise"
check PCI1 FIXED at-least 1 "$(git grep -nE 'vaults/pilot-smokeball' | n)" "instrument live: a live seat's vault path is found"
check I1a FIXED exact 0 "$(git grep -nE 'default="smd"' -- operator src scripts | n)" "no CLI defaults to the retired smd slug"
check I1b FIXED exact 0 "$(git grep -cE '^[[:space:]]+customer: smd$' -- operator/skills | n)" "no shipped skill frontmatter names the retired seat"
# I3 CLOSED 10-06: tests/portal-routes-bind-tenant.test.ts enumerates the tree.
check I3  FIXED at-least 1 "$(c 'api/portal' tests/portal-routes-bind-tenant.test.ts)" "portal routes' tenant binding is pinned by a test"
# I4 RESTATED 10-06: the 09-04 grep began matching casework_ledger's writer.
check I4  FIXED exact 1 "$(git grep -nE 'escalation_ledger\.append_line\(' -- operator | grep -v '/tests/' | n)" "one escalation-ledger writer, the witnessed one"
# I5 CLOSED 10-06: operator/tests/test_broker_writer_sync.py pins the twins.
check I5  FIXED at-least 1 "$(c 'broker_writer' operator/tests/test_broker_writer_sync.py)" "broker_writer.py twins pinned by a sync test"
# F9 CLOSED 10-06 (#2795): no library package mutates sys.path at import.
check F9  FIXED exact 0 "$(grep -rln 'sys.path.insert' operator/safety_substrate operator/bin/lib operator/workspace_broker --include='*.py' | grep -v /tests/ | n)" "no library package mutates sys.path at import"
check I13 FIXED exact 0 "$(for f in operator/customers/[a-z]*/customer.yaml; do npx --quiet tsx scripts/validate-customer-yaml.ts "$f" >/dev/null 2>&1 || echo x; done | n)" "every live seat customer.yaml validates"
check I14 FIXED exact 0 "$(git grep -nE '(hermes|HERMES\}?"?) +(-p +[^ ]+ +)?(-z|chat)( |$)' -- operator/bin operator/rehearsal scripts docs/skills .claude | grep -vE ':[0-9]+:[[:space:]]*#' | n)" "no executable runs hermes one-shot on a seat"
check PCI15 FIXED at-least 1 "$(git grep -nE '[a-z]+@smd\.services' -- src operator | n)" "instrument live: smd.services addresses found"
check I15 FIXED exact 0 "$(git grep -nE '[a-z0-9._-]+@venturecrane\.com' -- src operator scripts workers public | n)" "no venturecrane address in SMD code/config/skills"

# ============================================================ STILL OPEN
check F1  OPEN at-most 1 "$(grep -rn 'record_tool_failure\|record_refusal\|record_tool_success' operator/ --include='*.py' | grep -v test | grep -v 'sticky_stop.py:' | grep -v control-probes | n)" "sticky_stop arms have no code callers (a docstring)"
# I12 CLOSED 10-06 (#3067): callback events persist to oauth_callback_audit
# (migration 0121, applied on prod: vfy_01M499BC3Y6N669K5CBSY69BXZ).
check I12 FIXED exact 0 "$(c 'TODO(#891)' src/lib/oauth/audit.ts)" "OAuth consent audit persists to D1"

# 2026-10-06 fix wave (#3061 #3062 #3063 #3064 #3065 #3067): N1-N14, N16-N18
# and I12 flipped OPEN -> FIXED with the value measured on main after the
# merges. The expectations now read as REGRESSED if a defect returns. N15 (SR1
# other driver) stays OPEN: it is being fixed by the firm-letter session.
# =============================================== NEW 10-06: src/ scripts/ CI
check N1  FIXED exact 0 "$(git grep -n "strField(data, 'error')" -- src/scripts | n)" "assessment chat shows the API's message, not its code"
check N2  FIXED exact 0 "$(c 'operatorPriceCents ?? 0) : 0' src/pages/portal/billing/index.astro)" "billing list renders no amount for an unpriced subscription"
check N3  FIXED exact 0 "$(grep -rlE "[Ww]e('ll| will) (let you know|notify you|email you)" src --include='*.ts' --include='*.tsx' --include='*.astro' | n)" "no client surface promises a notice nothing sends"
check PCN4 FIXED at-least 1 "$(c 'tee gitleaks-output.txt' .github/workflows/security.yml)" "instrument live: the gitleaks step is found"
check N4  FIXED at-least 3 "$(c -E 'pipefail|shell: bash' .github/workflows/security.yml)" "gitleaks step runs with pipefail, so it can fail"
check PCN5 FIXED at-least 1 "$(c 'report.vulnerabilities' scripts/audit-allowlist.mjs)" "instrument live: the audit report is parsed"
check N5  FIXED at-least 1 "$(c 'report.error' scripts/audit-allowlist.mjs)" "npm audit error JSON fails the gate"
# N6 RESTATED: the fix swapped safeAll for mustRead, so the .ok grep cannot see it.
check N6  FIXED exact 1 "$(c "mustRead('unwitnessed certifications'" scripts/ci-reconcile-obligations.ts)" "a failed unwitnessed-certification read fails the run"
check N7  FIXED exact "false false" "$(node -e "import('./.claude/hooks/lib/register-grounding.mjs').then(m=>console.log(m.dateQuoteAnchorsDate('done by October 15, 2026.','2026-10-01'), m.dateQuoteAnchorsDate('due October 15, 2025','2026-10-15')))" 2>&1)" "register due-date guard refuses dates the quote does not state"
check N8  FIXED exact 1 "$(c 'process.stderr.write(summarize(result))' .claude/hooks/memory-audit.mjs)" "SessionStart findings reach context (the manual run keeps stderr)"

# ============================================= NEW 10-06: broker / medchron
check PCN9 FIXED at-least 1 "$(c PermissionError operator/workspace_broker/request_errors.py)" "instrument live: protocol exceptions are listed"
check N9  FIXED at-least 1 "$(c 'BrokerRefusal' operator/workspace_broker/request_errors.py)" "msgraph/AgentMail refusals keep their name and message"
check PCN10 FIXED at-least 1 "$(c LimitHold $MC/llm.py)" "instrument live: llm.py handles LimitHold"
check N10 FIXED at-least 12 "$(grep -r 'except LimitHold' $MC/audit/ $MC/stages/ | n)" "a cost hold mid-audit propagates and the job holds"
check N11 FIXED exact 0 "$(c 'if "|" in ln and "(" in ln and ln.strip() and not who' $MC/stages/scope.py)" "joint matter keeps the client's unlabelled blocks"
check PCN12 FIXED at-least 1 "$(c 'r = seat.add_file' $MC/stages/upload.py)" "instrument live: the upload call is found"
check N12 FIXED at-least 1 "$(c 'pending=True' $MC/stages/upload.py)" "upload writes an intent row before sending"

# ========================================== NEW 10-06: connectors / bin
N13_PY='from smokeball_connector.medicals_layout import indices_named as f
k = "Provider/DisplayName"; v = "Valley Northside Imaging Center"; s = "Northside Imaging Center"
print(f({0: {k: v}, 1: {k: s}}, s), f({0: {k: v}}, s))'
check N13 FIXED exact "[1] []" "$(PYTHONDONTWRITEBYTECODE=1 PYTHONPATH=operator/connectors/smokeball python3 -c "$N13_PY" 2>&1)" "Medicals provider match is exact; containment never selects a row"
check PCN14 FIXED at-least 1 "$(c pyyaml operator/pyproject.toml)" "instrument live: operator deps are read"
check N14 FIXED at-least 1 "$(( $(c cryptography operator/pyproject.toml) + $(c 'with cryptography' operator/bin/decommission-customer.sh) ))" "live decommission can sign its packet"
check PCN15 FIXED at-least 1 "$(c person $SB/sr1_form.py)" "instrument live: sr1_form checks person for the client"
check N15 OPEN exact 0 "$(grep -A4 'def _other_driver' $SB/sr1_form.py | grep -c person)" "SR1 prints a company as the other driver"

# ================================================ NEW 10-06: operator/skills
check N16 FIXED exact 0 "$(c 'handover_only=all(e.handover for e in listed)' operator/skills/task-list-keeper/review.py)" "closes-only task email has its own lead"
check N17 FIXED exact 0 "$(c 'cm.own_level and d.task_id and view.is_operator_task(cm, d.task_id, stamp)' operator/skills/deadline-miss-escalator/casework_filter.py)" "a handed-over Operator task reaches the digest"
check N18 FIXED exact 0 "$(c 'mattersTruncated` is true and the matter has' operator/skills/service-confirmation-watcher/SKILL.md)" "a matter with no memo row is unknown, never re-captured"

# ============================================== NEW 10-06: invariant pass
check PCN19 FIXED at-least 1 "$(c 'migrations/' docs/handbook/repository-map.md)" "instrument live: the migrations row is found"
check N19 FIXED exact 0 "$(c -E '\b[0-9]+ (forward )?migrations\b' docs/handbook/repository-map.md)" "repository map states no migration count (pinned in docs-facts)"

echo
echo "  $pass closed · $still_open still open · $regressed regressed · $drift changed"
[ "$regressed" -eq 0 ] || exit 1
exit 0
