#!/usr/bin/env bash
# Claims probe — generated by /code-review v2.
#
# Every fact re-derives itself. Two fields govern how a result is read:
#   state:     OPEN  = defect still stands   | FIXED = defect was fixed
#   direction: exact | at-most | at-least    (which way is improvement)
#
#   HOLDS + FIXED -> closed, skipped next run
#   HOLDS + OPEN  -> STILL-OPEN, carried into every report, never skipped
#   DRIFT + FIXED -> regression, loud
#   DRIFT + OPEN  -> improvement or change, re-measure
#
# Usage: bash docs/reviews/claims-2026-09-04.probe.sh
# Exit:  0 = nothing regressed, 1 = a FIXED claim broke or a shape check failed

cd "$(dirname "$0")/../.." || exit 2

pass=0; still_open=0; regressed=0; drift=0
REPORT="docs/reviews/claims-2026-09-04.md"

# ---------------------------------------------------------------- self-check
if [ -f "$REPORT" ]; then
  lines=$(grep -cve '^[[:space:]]*$' "$REPORT")
  grades=$(grep -cE '^\| [A-F][+-]? ' "$REPORT" || true)
  [ "$lines" -le 60 ] || { echo "SHAPE FAIL: report is $lines non-blank lines (max 60)"; exit 1; }
  [ "$grades" -eq 0 ] || { echo "SHAPE FAIL: report contains $grades letter-grade rows"; exit 1; }
  printf '  shape: %s non-blank lines, %s grade rows\n\n' "$lines" "$grades"
fi

# ------------------------------------------------------------------- checker
check() {
  local id="$1" state="$2" dir="$3" expected="$4" actual="$5" desc="$6"
  local ok=1
  case "$dir" in
    exact)    [ "$actual" = "$expected" ] || ok=0 ;;
    at-most)  [ "$actual" -le "$expected" ] 2>/dev/null || ok=0 ;;
    at-least) [ "$actual" -ge "$expected" ] 2>/dev/null || ok=0 ;;
  esac
  if [ "$ok" = 1 ] && [ "$state" = "FIXED" ]; then
    printf '  \033[32mHOLDS     \033[0m %-5s %s (= %s)\n' "$id" "$desc" "$actual"; pass=$((pass+1))
  elif [ "$ok" = 1 ] && [ "$state" = "OPEN" ]; then
    printf '  \033[33mSTILL-OPEN\033[0m %-5s %s (= %s)\n' "$id" "$desc" "$actual"; still_open=$((still_open+1))
  elif [ "$state" = "FIXED" ]; then
    printf '  \033[31mREGRESSED \033[0m %-5s %s expected %s %s, got %s\n' "$id" "$desc" "$dir" "$expected" "$actual"; regressed=$((regressed+1))
  else
    printf '  \033[36mCHANGED   \033[0m %-5s %s was %s %s, now %s — re-measure\n' "$id" "$desc" "$dir" "$expected" "$actual"; drift=$((drift+1))
  fi
}
# count of lines, whitespace-stripped, never failing the pipeline
n() { wc -l | tr -d ' '; }

echo "Claims for ss-console, 2026-09-04"
echo

# =================================================== CARRIED FROM 2026-08-25
pc6=$(grep -rniE "content-type|cache-control" src/ workers/ public/ wrangler.toml 2>/dev/null | n)
check PC6 FIXED at-least 1 "$pc6" "instrument is live (sibling header terms found)"
a6=$(grep -rniE "content-security-policy|x-frame-options|strict-transport-security|frame-ancestors" src/ workers/ public/ wrangler.toml 2>/dev/null | n)
check A6  FIXED at-least 4 "$a6" "security response headers exist in shipped code"
check A6w FIXED at-least 1 "$(grep -cE 'return applySecurityHeaders\(response, context\.request\.url\)' src/middleware.ts 2>/dev/null | tr -d ' ')" "headers applied by the middleware (call site, not import)"
check F3  FIXED at-least 1 "$(grep -c 'EXPECTED_VERBS' tests/broker-verb-registry.test.ts 2>/dev/null | tr -d ' ')" "broker verb set is pinned by a test"
check F4  FIXED at-least 1 "$(grep -c 'taintGateMembers' tests/operator-taint-gate.test.ts 2>/dev/null | tr -d ' ')" "taint-gate refusal set is pinned by a test"
check F7  FIXED at-least 20 "$(grep -c '\"copies\"' operator/contracts/pre-run-shared-symbols.json 2>/dev/null | tr -d ' ')" "vendored pre_run symbols under a sync contract"
check F12 FIXED exact    0  "$(grep -cE '^ *thresholds *:' vitest.config.ts 2>/dev/null | tr -d ' ')" "no unevaluatable coverage thresholds declared"
check F15 FIXED at-least 3  "$(grep -c 'redactOpaqueSegments' src/pages/api/events.ts 2>/dev/null | tr -d ' ')" "manage-token redaction wired"
check F17 FIXED at-least 1  "$(grep -c '{!disableAnalytics && <EventsTracker />}' src/layouts/Base.astro 2>/dev/null | tr -d ' ')" "EventsTracker honours disableAnalytics"

# F1 RESTATED: the 08-25 grep matched the table name, and the medchron daemon
# now READS sticky_stop_state (a consumer, not a caller of the arms). Match the
# arm methods only. The 1 remaining hit is a docstring in refusal.py.
check F1  OPEN at-most 1 "$(grep -rn 'record_tool_failure\|record_refusal\|record_tool_success' operator/ --include='*.py' | grep -v test | grep -v 'sticky_stop.py:' | grep -v control-probes | n)" "sticky_stop arms have no code callers (probed daily by control-probes.yml)"
# F9: 6 -> 7. The new library module is operator/bin/lib/sender_class.py (#2691).
check F9  OPEN at-most 7 "$(grep -rn 'sys.path.insert' operator/safety-substrate/ operator/bin/lib/ --include='*.py' | grep -v test | n)" "library modules mutate sys.path at import (+sender_class.py)"

# ====================================================== DIFF PASS A (src/)
# 2026-09-04 wave 1 (PRs #2695 #2696 #2697 #2698 #2699): A1-A5, B1-B6, I1a, I1b,
# I14, I15 flipped OPEN -> FIXED with the value measured on main at 66c89f61.
# The expectations below now read as REGRESSED if the defect returns.
# A1: first retainer invoice.paid dropped with a 200 when it beats
# checkout.session.completed; the handler never falls back to the
# smd_subscription_id the checkout stamps on the subscription's metadata.
check PCA1 FIXED at-least 1 "$(grep -c smd_subscription_id src/lib/stripe/subscriptions.ts | tr -d ' ')" "instrument live: checkout stamps smd_subscription_id"
check A1  FIXED at-least 1 "$(grep -c smd_subscription_id src/lib/webhooks/stripe-subscription-handler.ts | tr -d ' ')" "invoice handler has no fallback lookup by smd_subscription_id"
# A2: go-live promotion ignores checkout payment_status (ACH micro-deposit
# path goes active unpaid; async_payment_* not subscribed).
check A2  FIXED at-least 1 "$(grep -rn 'payment_status\|async_payment' src/pages/api/webhooks/stripe.ts src/lib/webhooks/ | n)" "checkout completion never reads payment_status"
# A3: same-filename amendment overwrites the earlier executed document (key
# hashes the NAME only; the upsert is DO UPDATE).
check A3  FIXED exact 0 "$(grep -c 'ON CONFLICT(storage_key) DO UPDATE' src/lib/db/operator-agreements.ts | tr -d ' ')" "agreement upsert overwrites an executed document on key collision"
# A4/A5: client-facing sentences not authored per engagement (Pattern A/B).
check A4  FIXED exact 0 "$(grep -c 'in force together' 'src/pages/portal/products/operator/[instance]/compliance/index.astro' | tr -d ' ')" "compliance page asserts contractual status in a template sentence"
check A5  FIXED exact 0 "$(grep -c 'Your subscription is active' src/pages/portal/billing/index.astro | tr -d ' ')" "billing banner states 'active' from ?start=done alone"

# ================================================ DIFF PASS B (operator/)
# B1: billing_docs rows carry id/name/pages (pages is never written by
# download.py) and billing.py reads t["path"]. Any matter with a billing-named
# document fails at billing_extract after the paid stages.
check B1  FIXED exact 0 "$(grep -c 'picked.append({"id": r.get("id"), "name": name, "pages": r.get("pages")})' operator/runners/medchron/medchron/decisions.py | tr -d ' ')" "billing_docs rows lack the path billing.py renders"
# B2: classify_scanned refuses without <data_root>/controls/controls.json and
# nothing on the seat seeds it into the daemon's per-job data_root.
check PCB2 FIXED at-least 1 "$(grep -c 'controls.json' operator/runners/medchron/medchron/stages/classify.py | tr -d ' ')" "instrument live: classify.py names controls.json"
check B2  FIXED at-least 1 "$(grep -l 'controls' operator/runners/medchron/medchron/daemon.py operator/runners/medchron/medchron/seat.py operator/runners/medchron/medchron/job.py operator/workspace_broker/medchron_verbs.py operator/templates/entrypoint.sh operator/templates/Dockerfile operator/bin/provision-customer.sh 2>/dev/null | n)" "no seat-side path seeds medchron controls"
# B3: send_verify joins dispatch to wake on skill_name; the broker's
# CONFIRM_SEND_DISPATCHED row never carries it, so every templated send holds.
check PCB3 FIXED at-least 1 "$(grep -c skill_name operator/workspace_broker/audit_ledger.py | tr -d ' ')" "instrument live: the ledger schema has skill_name"
check B3  FIXED at-least 1 "$(grep -c skill_name operator/workspace_broker/server.py | tr -d ' ')" "broker dispatch rows never carry skill_name"
# B4: return_link_unauthored is a seat-level absence but render.py treats only
# surface_config_missing as seat-level, so the line reads "matter number
# unavailable" (a resolution failure that did not happen).
check B4  FIXED at-least 1 "$(grep -c 'return_link_unauthored' operator/skills/client-verification-tracker/render.py | tr -d ' ')" "CVT render does not classify return_link_unauthored as seat-level"
# B5: held-job reason (file names, stage-log tail) reached the wake prompt
# with only a length cap. Fixed #2696: the wake names the stage; the ledger
# and console keep the full reason (a human reading their own tenant).
check B5  FIXED exact 0 "$(grep -c 'Reason: {fields' operator/runners/medchron/medchron/daemon.py | tr -d ' ')" "medchron wake carries no free-text reason"
check B5w FIXED at-least 1 "$(grep -c 'Held at:' operator/runners/medchron/medchron/daemon.py | tr -d ' ')" "medchron wake names the held stage only"
# B6: delivered chronology carries a first-person future-behaviour sentence.
check B6  FIXED exact 0 "$(grep -c 'we will extend' operator/runners/medchron/medchron/stages/limitations.py | tr -d ' ')" "chronology limitations section promises future behaviour"

# ============================================== INVARIANT PASS (whole tree)
# I1: the smd seat retired 2026-09-03 (#2692). Directory + registry are gated
# by tests/customer-slug-pattern.test.ts; these two are not.
check PCI1 FIXED at-least 1 "$(git grep -nE 'vaults/pilot-smokeball' | n)" "instrument live: a live seat's vault path is found"
check I1a FIXED exact 0 "$(git grep -nE 'default="smd"' -- operator src scripts | n)" "no CLI defaults to the retired smd slug (voice-ingest-corpus.py --slug)"
check I1b FIXED exact 0 "$(git grep -cE '^[[:space:]]+customer: smd$' -- operator/skills | n)" "no shipped skill frontmatter names the retired seat"
# I3: every portal API route scopes to a tenant; no test enumerates the tree
# the way tests/admin-routes-require-session.test.ts does for admin.
check I3  OPEN at-least 19 "$(grep -lE 'getPortalClient\(|resolveOperatorAccess\(|resolveHostedAgentAccess\(|authorizeAdvancedSettings\(|resolveProductAccess\(' $(find src/pages/api/portal -name '*.ts') | n)" "portal routes calling a tenant-scoping helper (20 routes; trust-ceiling.ts is a 410 stub)"
# I4: the escalation ledger has exactly one writer, and it is the witnessed
# one (validate_append's send_witness is keyword-only, no default).
check I4  FIXED exact 1 "$(git grep -nE 'append_line\(' -- operator | grep -v '/tests/' | grep -v 'def append_line' | n)" "one escalation-ledger writer, the witnessed one (#2603 is a runtime-proof gap)"
# I5: broker_writer.py twins differ only by docstring; nothing pins them.
check I5  OPEN at-most 4 "$(diff operator/skills/client-verification-tracker/broker_writer.py operator/skills/deadline-miss-escalator/broker_writer.py | n)" "broker_writer.py twins unpinned (diff lines; 4 = docstring only)"
# I12: TODO(#891) pinned by a test although #891 CLOSED 2026-05-22; OAuth
# audit events are console.log only; the token store falls open to a no-op.
check I12  OPEN exact 3 "$(cat src/lib/oauth/audit.ts tests/oauth-callback.test.ts | grep -cE 'TODO.*#891' | tr -d ' ')" "TODO(#891) still in code and pinned by a test"
check I12b OPEN exact 2 "$(grep -c 'createNoOpTokenStore()' src/lib/oauth/store.ts | tr -d ' ')" "OAuth token store falls open to a no-op returning ok:true"
# I13: live seat customer.yaml files validate (deploy-time only; no PR gate).
check I13 FIXED exact 0 "$(for f in operator/customers/[a-z]*/customer.yaml; do npx --quiet tsx scripts/validate-customer-yaml.ts "$f" >/dev/null 2>&1 || echo x; done | n)" "every live seat customer.yaml validates"
# I14: an executable starts a second hermes runtime on a seat (one-shot rule,
# operator/CLAUDE.md 2026-09-01).
check I14 FIXED exact 0 "$(git grep -nE '(hermes|HERMES\}?"?) +(-p +[^ ]+ +)?(-z|chat)( |$)' -- operator/bin operator/rehearsal scripts docs/skills .claude | grep -vE ':[0-9]+:[[:space:]]*#' | n)" "no executable runs hermes one-shot on a seat (mission-smoke-managed-gmail.sh)"
# I15: CLAUDE.md says the venturecrane address never appears in SMD code,
# config or skills; 15 of 17 are in a skill tree COPYed into every image.
check PCI15 FIXED at-least 1 "$(git grep -nE '[a-z]+@smd\.services' -- src operator | n)" "instrument live: smd.services addresses found"
check I15 FIXED exact 0 "$(git grep -nE '[a-z0-9._-]+@venturecrane\.com' -- src operator scripts workers public | n)" "venturecrane address in SMD code/config/skills"

echo
echo "  $pass closed · $still_open still open · $regressed regressed · $drift changed"
[ "$regressed" -eq 0 ] || exit 1
exit 0
