#!/usr/bin/env bash
# Claims probe — generated by /code-review v2.
#
# Every fact re-derives itself. Two fields govern how a result is read:
#   state:     OPEN  = defect still stands   | FIXED = defect was fixed
#   direction: exact | at-most | at-least    (which way is improvement)
#
#   HOLDS + FIXED -> closed, skipped next run
#   HOLDS + OPEN  -> STILL-OPEN, carried into every report, never skipped
#   DRIFT + FIXED -> regression, loud
#   DRIFT + OPEN  -> improvement or change, re-measure
#
# Usage: bash docs/reviews/claims-2026-08-25.probe.sh
# Exit:  0 = nothing regressed, 1 = a FIXED claim broke or a shape check failed

cd "$(dirname "$0")/../.." || exit 2

pass=0; still_open=0; regressed=0; drift=0
REPORT="docs/reviews/claims-2026-08-25.md"

# ---------------------------------------------------------------- self-check
# The deliverable polices its own shape, so "report under 60 lines" is a control
# rather than an intention. v1's failure was self-assessment of self-authored
# output; a number cannot be talked past.
if [ -f "$REPORT" ]; then
  lines=$(grep -cve '^[[:space:]]*$' "$REPORT")
  grades=$(grep -cE '^\| [A-F][+-]? ' "$REPORT" || true)
  [ "$lines" -le 60 ] || { echo "SHAPE FAIL: report is $lines non-blank lines (max 60)"; exit 1; }
  [ "$grades" -eq 0 ] || { echo "SHAPE FAIL: report contains $grades letter-grade rows"; exit 1; }
  printf '  shape: %s non-blank lines, %s grade rows\n\n' "$lines" "$grades"
fi

# ------------------------------------------------------------------- checker
check() {
  local id="$1" state="$2" dir="$3" expected="$4" actual="$5" desc="$6"
  local ok=1
  case "$dir" in
    exact)    [ "$actual" = "$expected" ] || ok=0 ;;
    at-most)  [ "$actual" -le "$expected" ] 2>/dev/null || ok=0 ;;
    at-least) [ "$actual" -ge "$expected" ] 2>/dev/null || ok=0 ;;
  esac

  if [ "$ok" = 1 ] && [ "$state" = "FIXED" ]; then
    printf '  \033[32mHOLDS     \033[0m %-5s %s (= %s)\n' "$id" "$desc" "$actual"; pass=$((pass+1))
  elif [ "$ok" = 1 ] && [ "$state" = "OPEN" ]; then
    printf '  \033[33mSTILL-OPEN\033[0m %-5s %s (= %s)\n' "$id" "$desc" "$actual"; still_open=$((still_open+1))
  elif [ "$state" = "FIXED" ]; then
    printf '  \033[31mREGRESSED \033[0m %-5s %s expected %s %s, got %s\n' "$id" "$desc" "$dir" "$expected" "$actual"; regressed=$((regressed+1))
  else
    printf '  \033[36mCHANGED   \033[0m %-5s %s was %s %s, now %s — re-measure\n' "$id" "$desc" "$dir" "$expected" "$actual"; drift=$((drift+1))
  fi
}

echo "Claims for ss-console, 2026-08-25"
echo

# ============================================================ ABSENCE LANE ===
# A6: security response headers. WAS the absence; now the presence.
#
# The 2026-08-25 run recorded this OPEN with a positive control (PC6) proving
# the instrument could return non-zero. It was true at BOTH layers — the repo
# grep returned 0, and `curl -sSIL https://portal.smd.services/` returned 0
# while the same command found `content-type`. Closed 2026-08-24 by
# src/lib/security/response-headers.ts, wired in src/middleware.ts around the
# WHOLE request so redirects and 401/403 denials carry the headers too.
#
# PC6 is retained. An absence claim that flips to a presence claim still needs
# its instrument shown live, because the same broken search that reports "0
# headers" would report "0 headers" after a correct fix.
pc6=$(grep -rniE "content-type|cache-control" src/ workers/ public/ wrangler.toml 2>/dev/null | wc -l | tr -d ' ')
check PC6 FIXED at-least 1 "$pc6" "instrument is live (sibling header terms found)"

a6=$(grep -rniE "content-security-policy|x-frame-options|strict-transport-security|frame-ancestors" \
       src/ workers/ public/ wrangler.toml 2>/dev/null | wc -l | tr -d ' ')
check A6 FIXED at-least 4 "$a6" "security response headers exist in shipped code"

# Built is not wired. The module can be perfect and unreachable.
#
# MATCH THE CALL, NOT THE NAME. The first version of this check counted every
# occurrence of `applySecurityHeaders` in the middleware and required >=1.
# Deleting the CALL left the IMPORT, the count went 2 -> 1, and the probe
# reported HOLDS on a middleware that no longer set a single header. Caught by
# tampering the target, which is the only reason it is not still wrong.
a6w=$(grep -cE 'return applySecurityHeaders\(response, context\.request\.url\)' src/middleware.ts 2>/dev/null | tr -d ' ')
check A6w FIXED at-least 1 "$a6w" "headers applied by the middleware (call site, not import)"

# ============================================== NOW ENFORCED BY npm run verify
# These five stopped being claims a review re-derives and became checks a merge
# is gated on. The probe's remaining job is to confirm the ENFORCEMENT is still
# wired — a test file that gets deleted takes its finding with it, silently.
check F3  FIXED at-least 1 "$(grep -c 'EXPECTED_VERBS' tests/broker-verb-registry.test.ts 2>/dev/null | tr -d ' ')" "broker verb set is pinned by a test"
check F4  FIXED at-least 1 "$(grep -c 'taintGateMembers' tests/operator-taint-gate.test.ts 2>/dev/null | tr -d ' ')" "taint-gate refusal set is pinned by a test"
check F7  FIXED at-least 20 "$(grep -c '\"copies\"' operator/contracts/pre-run-shared-symbols.json 2>/dev/null | tr -d ' ')" "vendored pre_run symbols under a sync contract"
check F12 FIXED exact    0  "$(grep -cE '^ *thresholds *:' vitest.config.ts 2>/dev/null | tr -d ' ')" "no unevaluatable coverage thresholds declared"

# ================================================== STILL OPEN — JUDGMENT ====
# F1: sticky_stop's arms have no dispatch caller. NOT a missing check — it is
# already probed daily by .github/workflows/control-probes.yml
# (probe_sticky_stop_arm_unwired), whose caller search excludes tests on purpose
# because "a test calling a circuit breaker is exactly the evidence that fooled
# everyone about sticky_stop for two months". The system knows. What is open is
# a product decision — wire the breaker or delete it — and that is the Captain's,
# not a gate's.
check F1  OPEN at-most  2   "$(grep -rn 'sticky_stop\|record_tool_failure\|record_refusal' operator/ --include='*.py' 2>/dev/null | grep -v test | grep -v control-probes | grep -v 'sticky_stop.py:' | wc -l | tr -d ' ')" "sticky_stop has no code callers (already probed daily)"

# F9: RESTATED. "28 sys.path.insert" mixed two different things. 22 are in
# executable entrypoints (operator/bin/*.py, rehearsal runners, seed scripts),
# where adding operator/ to the path is ordinary script behaviour. 6 are in
# LIBRARY modules that mutate sys.path at import time — importing them has a
# global side effect on the importing process. Only the second group is a smell,
# and its fix is packaging the operator tree, which is a live-runtime refactor
# and a design call rather than a defect. Measured precisely so the next review
# argues about the right number.
check F9  OPEN at-most  6   "$(grep -rn 'sys.path.insert' operator/safety-substrate/ operator/bin/lib/ --include='*.py' 2>/dev/null | grep -v test | wc -l | tr -d ' ')" "library modules mutate sys.path at import"

# ================================================================== FIXED ====
check F15 FIXED at-least 3  "$(grep -c 'redactOpaqueSegments' src/pages/api/events.ts 2>/dev/null | tr -d ' ')" "manage-token redaction wired"
check F17 FIXED at-least 1  "$(grep -c '{!disableAnalytics && <EventsTracker />}' src/layouts/Base.astro 2>/dev/null | tr -d ' ')" "EventsTracker honours disableAnalytics"

echo
echo "  $pass closed · $still_open still open · $regressed regressed · $drift changed"
[ "$regressed" -eq 0 ] || exit 1
exit 0
