"""What the evidence packet writes: the README and the three dump serializers.

Split out of :mod:`adapter.evidence.packet` (2026-09-11, code review 2026-09-10,
Architecture 2): the builder there stays the orchestrator; this module renders
bytes from values the builder already holds. It reads nothing.

The README is the one page a non-technical reader is expected to open, so
its wording carries the packet's honesty: the coverage statement sits above
the contents list, the signed and unsigned cases say what can and cannot be
verified, and no sentence promises behaviour the customer did not contract.
No em dashes (style rule).
"""

from __future__ import annotations

import csv
import io
import json
from typing import Any, Iterable, Sequence

from .packet_sources import AuditCoverage, ChainPin


# ---------------------------------------------------------------------------
# Serialization helpers
# ---------------------------------------------------------------------------


def _rows_to_csv(rows: Iterable[dict], columns: Sequence[str]) -> bytes:
    buf = io.StringIO()
    writer = csv.DictWriter(buf, fieldnames=list(columns), extrasaction="ignore")
    writer.writeheader()
    for row in rows:
        writer.writerow({c: ("" if row.get(c) is None else row.get(c)) for c in columns})
    return buf.getvalue().encode("utf-8")


def _rows_to_json(payload: Any) -> bytes:
    return json.dumps(payload, sort_keys=True, indent=2, default=str).encode("utf-8")


def _render_yaml(data: Any) -> bytes:
    """Render a parsed yaml structure back to a stable YAML-ish string.

    The builder avoids importing PyYAML so the adapter does not pick up
    an optional dep. The output is human-readable and deterministic.
    JSON is a valid YAML 1.2 subset, which is enough for the packet's
    audit purpose.
    """
    return (json.dumps(data, sort_keys=True, indent=2, ensure_ascii=False, default=str) + "\n").encode("utf-8")


def _readme_text(
    *,
    customer_slug: str,
    customer_name: str,
    period_start: str,
    period_end: str,
    matter: str,
    signer_name: str,
    signer_email: str,
    actor: str,
    actor_role: str,
    manifest_sha256: str,
    coverage: AuditCoverage,
    chain_pin: ChainPin,
    signed: bool = False,
    key_id: str = "",
) -> bytes:
    """Render the plain-language README first page.

    No em dashes (style rule). No fabricated promises about behavior
    the customer did not contract: the README describes only what the
    packet itself contains.

    The coverage statement sits above the contents list on purpose. A
    reader who stops after the first screen must still learn what this
    packet cannot answer.
    """
    coverage_body = "\n\n".join(coverage.narrative_lines())
    pin_body = "\n\n".join(chain_pin.narrative_lines())
    body = (
        f"# Compliance Evidence -- {customer_name}\n\n"
        f"**Customer slug:** {customer_slug}\n"
        f"**Matter scope:** {matter}\n"
        f"**Period covered:** {period_start} to {period_end}\n"
        # Two different facts, deliberately not merged. The entity is who
        # stands behind the packet; the actor is who ran the export. Collapsing
        # them into one "generated by" line is how the signature block came to
        # name an individual in the first place (ss-console #2122).
        f"**Produced and signed by:** {signer_name} ({signer_email})\n"
        f"**Export run by:** {actor} ({actor_role})\n"
        f"**Manifest SHA-256:** {manifest_sha256}\n\n"
        "## What this package is\n\n"
        "This package documents how the Operator operated inside this "
        "customer instance during the period above. It is meant to be read "
        "by an attorney, an outside auditor, or the customer itself. You "
        "do not need a technical background to read this README or the "
        "summary PDF.\n\n"
        "## What this package covers, and what it cannot\n\n"
        f"{coverage_body}\n\n"
        "## Whether the log itself is complete\n\n"
        f"{pin_body}\n\n"
        "## What is in the package\n\n"
        "- `00-README.md` -- this document\n"
        "- `01-summary.pdf` -- the Susan-readable narrative\n"
        "- `03-audit-log.csv` -- every audit_log row for the period\n"
        "- `05-customer-yaml.redacted.yml` -- the customer's config, with "
        "secrets and OAuth scopes redacted\n"
        "- `06-memory-snapshot.json` -- the agent's memory rules, "
        "person mappings, and voice metadata\n"
        "- `07-skill-catalog.json` -- the skills active during the period\n"
        "- `09-boot-checks.csv` -- the substrate's invariant boot-check log\n"
        "- `manifest.json` -- file hashes plus the signature block\n"
        + ("- `manifest.sig` -- detached Ed25519 signature over `manifest.json`\n\n" if signed else "\n")
        + "## What this package does NOT contain\n\n"
        "Substantive content of drafts, sent messages, or memory payloads "
        "is not in this packet. Those bodies live in per-customer R2 "
        "storage keyed by SHA-256 digest; the audit log records every "
        "digest, and an auditor can request the underlying object on "
        "demand against the customer's data-processing addendum.\n\n"
        "Voice sample bodies are not in this packet by default. Use the "
        "separate signed export path "
        "(`operator/bin/export-voice-samples.sh`) when full bodies are "
        "required.\n\n"
        # ss-console#2501. A digest an outsider cannot recompute asks the
        # reader to take SMD's word for it, which is the opposite of what an
        # evidence packet is for. The recipe differs per transport because the
        # transports differ: one carries our bytes verbatim, the other composes
        # the stored message itself. Stating that plainly is the honest move;
        # a single recipe that quietly failed on the reply path would be worse
        # than none.
        "## Checking a message against your own copy\n\n"
        "You can check a message body the Operator sent against the copy "
        "your own mail system stored, using nothing from SMD. The check "
        "does not depend on this packet being honest, which is the point of "
        "it.\n\n"
        "Rows for messages the Operator sent as a REPLY carry these "
        "hashes. A message the Operator sent on its own initiative records "
        "a hash of the whole send request rather than of the body bytes, so "
        "the check below does not apply to it; the row will simply not "
        "carry these fields.\n\n"
        "- `body_digest` is internal. It covers the subject and the body "
        "joined together, which is what our content checks read. The subject "
        "is not part of a reply on the wire, so this one cannot be "
        "reproduced from the message you hold. Do not try.\n"
        "- `body_digest_authored` is the SHA-256 of exactly the plain-text "
        "bytes the Operator handed to the mail system.\n"
        "- `body_digest_authored_html` is the same for the HTML body, when "
        "one was sent.\n\n"
        "**Which check applies depends on what your mail system did with "
        "the body, and the difference is not a technicality.** Where the "
        "mail system stores the bytes it was handed, the test is EQUALITY: "
        "the hash of the stored body equals the hash on the row. Where the "
        "mail system COMPOSES the stored message, the test is CONTAINMENT: "
        "the authored text must appear, byte for byte, inside the stored "
        "body, and its hash will never equal the whole.\n\n"
        "Microsoft Graph composes. A reply sent through it "
        "(`POST /messages/{id}/reply`) gets Microsoft's own HTML wrapper "
        "and the quoted original appended beneath what we wrote, so the "
        "stored body is LONGER than what the Operator authored and equality "
        "cannot hold. Use containment for those. Where the message went out "
        "through a transport that carries a real plain-text part, equality "
        "holds on that part. If you do not know which applies to a "
        "particular message, run the containment check: it holds in both "
        "cases.\n\n"
        "Equality, worked. Save the stored body to `stored.txt` exactly as "
        "your mail system holds it, with no re-wrapping and no added "
        "newline, then:\n\n"
        "```\n"
        "openssl dgst -sha256 stored.txt\n"
        "```\n\n"
        "Compare that hex value to `body_digest_authored` on the row (or to "
        "`body_digest_authored_html` if you saved the HTML body). They match "
        "or they do not; there is no partial credit.\n\n"
        "Containment, worked. Here you hold the stored message and we hold "
        "nothing you have to trust, so the check runs in two steps. Save "
        "the whole stored body to `stored.txt`. Then save the part of it "
        "you take to be what the Operator wrote, which on a Graph reply is "
        "everything above the quoted original, to `candidate.txt`, keeping "
        "its bytes exactly as they appear:\n\n"
        "```\n"
        "grep -F -f candidate.txt stored.txt\n"
        "openssl dgst -sha256 candidate.txt\n"
        "```\n\n"
        "The first prints the matching lines and exits 0 when your "
        "candidate is present verbatim, which is what makes the boundary "
        "you drew legitimate rather than convenient; it exits 1 when it is "
        "not. The second must equal `body_digest_authored_html` on the row "
        "when your candidate is HTML, or `body_digest_authored` when it is "
        "plain text. Both together are the proof: the bytes you extracted "
        "are inside the message you hold, AND they are the bytes the "
        "Operator handed the mail system.\n\n"
        "Whether the hashes match is a fact about your mail system, not a "
        "promise from us. If it stored what it was handed, they match. If "
        "it re-encoded the body on the way in, by re-wrapping lines or "
        "changing the character encoding, they will not, and that "
        "difference is itself something worth knowing rather than "
        "something we should have hidden by hashing a normalized copy.\n\n"
        "We do not normalize, reformat, or canonicalize anything before "
        "hashing, and neither should you. A recipe that first massages the "
        "bytes is a recipe someone can argue with.\n\n"
        "What a match proves: the body on that row is the body your mail "
        "system stored. What it does not prove on its own: that the row "
        "itself was not altered. That is what the hash chain and the "
        "signature below are for.\n\n"
        "## Verification\n\n"
        + (
            (
                "**This packet is SIGNED.** `manifest.sig` is a detached "
                "Ed25519 signature over the exact bytes of `manifest.json`, "
                "which in turn carries the SHA-256 of every other file. "
                "Verification needs no credential and no contact with SMD.\n\n"
                "The signer of record is SMDurgan, LLC, the company under "
                "contract with this firm. The packet is not signed by an "
                "individual, so it stays verifiable regardless of who is "
                "employed here when you read it.\n\n"
                "Every signing key SMD has ever used is published at "
                "https://smd.services/trust, with its fingerprint and its "
                "status. That page is a standing commitment: the address does "
                "not change, and a retired key stays published so packets "
                "signed under it remain verifiable.\n\n"
                "Fetch the current public key from "
                "https://smd.services/keys/evidence-packet-signing-key.pem "
                f"and confirm its fingerprint is `{key_id}`, the key named in "
                "`manifest.json`. If it is not, the packet was signed under an "
                "earlier key: find that fingerprint on the trust page and "
                "fetch that key instead. Then:\n\n"
                "```\n"
                "openssl pkeyutl -verify -pubin "
                "-inkey evidence-packet-signing-key.pem \\\n"
                "  -rawin -in manifest.json -sigfile manifest.sig\n"
                "```\n\n"
                "A successful verification proves the manifest was produced "
                "by SMD and has not been altered since export. Once it "
                "passes, hash any individual file and compare it to its entry "
                "in `manifest.json`.\n\n"
                "The signature covers origin and integrity after export. It "
                "says nothing about whether the underlying audit log is "
                "correct. Tamper evidence within the log itself is a separate "
                "mechanism: the ledger is hash chained, so a row altered, "
                "removed, or inserted anywhere before the end of the log "
                "breaks the chain at a verifiable point. Rows removed from the "
                "END of the log are a separate question, answered by the "
                "section above.\n\n"
            )
            if signed
            else (
                "**This packet is UNSIGNED. Its integrity is not "
                "cryptographically verifiable.** No signing key was "
                "configured when it was generated, so `manifest.json` carries "
                "no signature and there is no `manifest.sig`. The SHA-256 "
                "values quoted inside this packet (this README and the "
                "summary PDF) prove only that the packet is internally self-"
                "consistent. They are stored in the same archive they "
                "describe, so on their own they cannot detect deliberate "
                "tampering.\n\n"
                "To check integrity, compare the manifest SHA-256 above "
                "against the value recorded OUT OF BAND when the packet was "
                "generated: the `COMPLIANCE_PACKET_EXPORTED` audit-log row's "
                "`manifest_sha256`, obtained directly from the firm or SMD "
                "rather than from this archive. Once the manifest hash "
                "matches that external record, hash any individual file and "
                "compare it to its entry in `manifest.json`.\n\n"
            )
        )
        + "## Questions\n\n"
        f"Contact: {signer_email}\n"
    )
    return body.encode("utf-8")
