# ============================================================================
# GENERATED by operator/bin/gen-env-arrays.py from
# operator/contracts/env-consumption.yaml — the single source of truth.
# DO NOT EDIT BY HAND. Regenerate:  python3 operator/bin/gen-env-arrays.py
# CI asserts this file is in sync (operator/bin/tests/test_env_array_generation.py).
#
# REQUIRED_ENV = contract vars (requirement: required) whose stage reaches the
# Machine (boot|agent|broker). OPTIONAL_ENV = likewise for requirement: optional.
# ============================================================================
REQUIRED_ENV=(
  ANTHROPIC_API_KEY
  R2_ACCESS_KEY_ID
  R2_BUCKET_CONFIG
  R2_SECRET_ACCESS_KEY
  R2_SKILL_BODIES_BUCKET
  SMD_D1_AUDIT_BINDING
)

OPTIONAL_ENV=(
  AGENTMAIL_API_KEY
  AGENTMAIL_SEND_API_KEY
  GOOGLE_CLIENT_SECRET_JSON
  GOOGLE_SERVICE_ACCOUNT_JSON
  GOOGLE_TOKEN_JSON
  HONCHO_API_KEY
  MSGRAPH_CLIENT_ID
  MSGRAPH_CLIENT_SECRET
  MSGRAPH_MAILBOX
  MSGRAPH_SEND_CLIENT_ID
  MSGRAPH_SEND_CLIENT_SECRET
  MSGRAPH_SEND_TENANT_ID
  MSGRAPH_TENANT_ID
  R2_ENDPOINT_URL
  R2_SKILL_BODIES_ACCESS_KEY_ID
  R2_SKILL_BODIES_SECRET_ACCESS_KEY
  SMD_AUDIT_BROKER_SOCKET
  SMD_D1_AGENT_STATE_BINDING
  SMD_D1_OBSERVATIONS_BINDING
  SMD_DIRECT_WRITE_ACTOR
  SMD_GATEWAY_PID
  SMD_SPEC_DIR
  SMD_VOICE_VAULT_DIR
  SMOKEBALL_OAUTH_STATE_KEY
  TELEGRAM_ALLOWED_USERS
  TELEGRAM_BOT_TOKEN
)
